### ISSUE TITLE
Any way to use relative links (by not adding http)? 

### ISSUE THREAD

**Issue by cousinisaac** [Jeradin/acf-website-field#23]
This is a great add-on that saves me time. Thanks for the good work! 

And, it would be even better if the admin could choose to enable the automatic adding of "http://" or force the content editor to add it manually so that they can use relative links with out the "http://" if so desired. 

One use case for this is when you have a staging server and want to create links to pages on staging and have them still work when exporting the content to production without having to edit the links again or do a find-and-replace on the database. 

It would be extra nice to add wordpress's link picker tool. I imagine Links picked with that tool would be dynamic and thus their base url would change when imported to another server. 

Anyway, just my two cents. 

Thanks again,

 isaac

**Comment by jeremyschuler** [comment]
A quick workaround is to use the field type 'text'.  For example: 

**Venue Link**
Insert relative link to venue page. ie. /page-slug

`<?php
    if(get_field('venue_url')) {
        echo '<a href="' . get_field('venue_url') . '">Venue Info</a>';
    }
?>`
