### ISSUE TITLE
No options in 5.1

### ISSUE THREAD

**Issue by gil--** [Jeradin/acf-website-field#32]
I'm using Advanced Custom Fields Pro 5.1 and there are no options to allow for a title or open in new window:
![screen shot 2015-01-21 at 1 00 15 pm](https://cloud.githubusercontent.com/assets/3484527/5841780/8a04917c-a16d-11e4-8ba9-04e96c7c8f30.png)

Any idea what's up? It basically looks and functions the same as a url field right now.

**Comment by Jeradin** [comment]
Very sorry for not seeing this sooner. Way too late, but it is fixed now.
